name: cursor-editor
base: core24
version: '0.40.4'
title: Cursor
summary: Cursor
description: Cursor is a Code Editor Built for Programing with AI
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  cursor-editor:
    plugin: dump
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL
      cp -r $SNAPCRAFT_PART_SRC/squashfs-root/* $SNAPCRAFT_PART_INSTALL/
      cp cursor.desktop $SNAPCRAFT_PART_INSTALL/
      cp cursor.png $SNAPCRAFT_PART_INSTALL/
    prime:
      - .
    stage-packages:
      - libnss3
      - libatk1.0-0t64
      - libatk-bridge2.0-0t64
      - libcups2t64
      - libasound2t64
      - libcairo2
      - libdbus-glib-1-2
      - libdbusmenu-glib4
      - libgbm1
      - libgdk-pixbuf-2.0-0
      - libgtk-3-0t64
      - libgtk2.0-0t64
      - libpango-1.0-0
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxkbfile1
      - libxrandr2
      #   - libglib2.0-0
      #   - libfuse2t64

apps:
  cursor-editor:
    command: ./cursor --no-sandbox
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - unity7
      - browser-support
      - network
      - gsettings
      - audio-playback
      - pulseaudio
      - opengl
    desktop: cursor.desktop
