name: cursor-editor
base: core24
version: '0.40.4'
title: Cursor
summary: Cursor
description: Cursor is a Code Editor Built for Programing with AI
grade: stable
confinement: strict

parts:
  cursor-editor:
    plugin: dump
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL
      cp -r $SNAPCRAFT_PART_SRC/squashfs-root/* $SNAPCRAFT_PART_INSTALL/
      cp cursor.desktop $SNAPCRAFT_PART_INSTALL/
      cp command.sh $SNAPCRAFT_PART_INSTALL/
    prime:
      - .
    stage-packages:
      - libasound2t64
      - libatk-bridge2.0-0t64
      - libatk1.0-0t64
      - libcairo2
      - libcups2t64
      - libdbus-glib-1-2
      - libdbusmenu-glib4
      - libgbm1
      - libgdk-pixbuf-2.0-0
      - libgtk-3-0t64
      - libgtk2.0-0t64
      - libnss3
      - libpango-1.0-0
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxkbfile1
      - libxrandr2

apps:
  cursor-editor:
    command: command.sh
    extensions: [gnome]
    environment:
      HOME: "$SNAP_USER_COMMON"
    plugs:
      - home
      - browser-support
      - network
      - audio-playback
      - pulseaudio
      - process-control
      - system-observe
    desktop: cursor.desktop
